################################################################################
#
# German messages for hv.tcl 
#
# Richard Suchenwirth <Richard.Suchenwirth-Bauersachs@siemens.com>
#
################################################################################

::msgcat::mcset de "No index found!" 	"Kein Index gefunden!"
::msgcat::mcset de "Help" 		"Hilfe"
::msgcat::mcset de "Table of content" 	"Inhaltsverzeichnis"
::msgcat::mcset de "Previous" 		"Vorheriges"
::msgcat::mcset de "Next" 		"Nächstes"
::msgcat::mcset de "Exit" 		"Beenden"