################################################################################
#
# French messages for hv.tcl 
#
# David Zolli aka kroc <kroc@kroc.tk>
#
################################################################################

::msgcat::mcset fr "No index found!" 	"Index introuvable !"
::msgcat::mcset fr "Help" 		"Aide"
::msgcat::mcset fr "Table of content" 	"Table des matières"
::msgcat::mcset fr "Previous" 		"Précédent"
::msgcat::mcset fr "Next" 		"Suivant"
::msgcat::mcset fr "Exit" 		"Quitter"