################################################################################
#
# Italian messages for hv.tcl 
#
# Salvatore Sanfilippo <antirez@invece.org>
#
################################################################################

::msgcat::mcset it "No index found!" 	"Nessun indice trovato !"
::msgcat::mcset it "Help" 		"Aiuto"
::msgcat::mcset it "Table of content" 	"Indice"
::msgcat::mcset it "Previous" 		"Precedente"
::msgcat::mcset it "Next" 		"Successivo"
::msgcat::mcset it "Exit" 		"Uscita"