################################################################################
#
# Dutch messages for hv.tcl 
#
# Arjen Markus <arjen.markus@wldelft.nl>
#
################################################################################

::msgcat::mcset nl "No index found!" 	"Index niet gevonden!"
::msgcat::mcset nl "Help" 		"Informatie"
::msgcat::mcset nl "Table of content" 	"Inhoudsopgave"
::msgcat::mcset nl "Previous" 		"Vorige"
::msgcat::mcset nl "Next" 		"Volgende"
::msgcat::mcset nl "Exit" 		"Einde"