################################################################################
#
# Swedish messages for hv.tcl 
#
# Peter Spjuth <peter.spjuth@space.se>
#
################################################################################

::msgcat::mcset se "No index found!"	"Hittade inget index!"
::msgcat::mcset se "Help" 		"Hjälp"
::msgcat::mcset se "Table of content"	"Innehåll"
::msgcat::mcset se "Previous"		"Föregående"
::msgcat::mcset se "Next" 		"Nästa"
::msgcat::mcset se "Exit" 		"Avsluta"