################################################################################
#
# Spannish messages for hv.tcl 
#
# Miguel Sofer <mig@utdt.edu>
#
################################################################################

::msgcat::mcset sp "No index found!" 	"¡No se encontraron índices!"
::msgcat::mcset sp "Help" 		"Ayuda"
::msgcat::mcset sp "Table of content" 	"Tabla de contenido"
::msgcat::mcset sp "Previous" 		"Anterior"
::msgcat::mcset sp "Next" 		"Próximo"
::msgcat::mcset sp "Exit" 		"Salir"